server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always